language: rust
dist: trusty
cache:
  apt: true
  cargo: true
sudo: required
matrix:
  include:
  - os: linux
    rust: stable
    env: "FEATURE_OPTS=''"
  - os: osx
    rust: stable
    # Disable OpenSSL on MacOS X, because it's annoying to debug this on
    # Travis.  PRs to re-enable this are welcome.
    env: "FEATURE_OPTS='--no-default-features'"
script:
- cargo build $FEATURE_OPTS
- cargo test $FEATURE_OPTS
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/717bec1dd1d6de43c44c"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
