language: rust
dist: trusty
cache:
  apt: true
  cargo: true
  pip: true
  directories:
  - "$TRAVIS_BUILD_DIR/target"
  - "$HOME/Library/Python/2.7"
sudo: required
matrix:
  include:
  - os: linux
    rust: stable
    env: "FEATURE_OPTS=''"
  - os: osx
    rust: stable
    # Disable OpenSSL on MacOS X, because it's annoying to debug this on
    # Travis.  PRs to re-enable this are welcome.
    env: "FEATURE_OPTS='--no-default-features'"
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$HOME/.cargo/bin:$PATH
script:
- |
  travis-cargo build -- $FEATURE_OPTS &&
  travis-cargo test -- $FEATURE_OPTS
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/717bec1dd1d6de43c44c"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
