[package]
name = "bollard"
description = "An asynchronous Docker daemon API"
version = "0.7.2"
authors = [ "Bollard contributors" ]
license = "Apache-2.0"
homepage = "https://github.com/fussybeaver/bollard"
repository = "https://github.com/fussybeaver/bollard"
documentation = "https://docs.rs/bollard"
readme = "README.md"
keywords = ["docker"]
edition = "2018"

[features]
# Enable tests specifically for the http connector
test_http = []
# Enable tests specifically for rustls
test_ssl = []

[dependencies]
arrayvec = "0.5.1"
base64 = "0.12.3"
bytes = "0.5.5"
chrono = { version = "0.4.11", features = ["serde"] }
dirs = "3.0.0"
env_logger = "0.7.1"
hex = "0.4.2"
http = "0.2.1"
hyper = "0.13.6"
hyper-rustls = "0.20.0"
log = "0.4.8"
pin-project = "0.4.22"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.55"
serde_urlencoded = "0.6.1"
tokio = { version = "0.2.17", features = ["time", "fs"] }
url = "2.1.1"
futures-core = "0.3.4"
futures-util = "0.3.4"
tokio-util = { version = "0.3.1", features = ["codec"] }
bollard-stubs = { version = "1.40.3" }
thiserror = "1.0"
rustls = "0.17"
rustls-native-certs = "0.3.0"
ct-logs = "0.7.0"
webpki-roots = "0.20.0"

[dev-dependencies]
tokio-executor = "0.2.0-alpha.6"
flate2 = "1.0.14"
tar = "0.4.29"

[target.'cfg(unix)'.dependencies]
hyperlocal =  { version = "0.1.4", package = "hyper-unix-connector" }

[target.'cfg(windows)'.dependencies]
mio-named-pipes = "0.1.6"
winapi = "0.3.9"
