[package]
name = "bollard"
description = "An asynchronous Docker daemon API"
version = "0.4.0-alpha.1"
authors = [ "Bollard contributors" ]
license = "Apache-2.0"
homepage = "https://github.com/fussybeaver/bollard"
repository = "https://github.com/fussybeaver/bollard"
documentation = "https://docs.rs/bollard"
readme = "README.md"
keywords = ["docker"]
edition = "2018"

[features]
# Enable OpenSSL both directly and for Hyper
ssl = ["openssl", "hyper-openssl"]
# Enable native-tls both directly for Hyper
tls = ["native-tls", "hyper-tls"]
# Enable tests specifically for the http connector
test_http = []
# Enable tests specifically for the tls connector
test_tls = []

[dependencies]
arrayvec = "0.5.1"
base64 = "0.11.0"
bytes = "0.5.3"
chrono = { version = "0.4.10", features = ["serde"] }
dirs = "2.0.2"
env_logger = "0.7.1"
failure = "0.1.6"
hex = "0.4.0"
http = "0.2.0"
hyper = "0.13.1"
hyper-openssl = { version = "0.8.0", optional = true }
hyper-tls = { version = "0.4.0", optional = true }
log = "0.4.8"
mio = "0.6.21"
native-tls = { version = "0.2.3", optional = true }
openssl = { version = "0.10.26", optional = true }
pin-project = "0.4.6"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
tokio = { version = "0.2.5", features = ["time"] }
url = "2.1.0"
futures-core = "0.3.1"
futures-util = "0.3.1"
tokio-util = { version = "0.2.0", features = ["codec"] }

[dev-dependencies]
tokio-executor = "0.2.0-alpha.6"
flate2 = "1.0.13"
tar = "0.4.26"

[target.'cfg(unix)'.dependencies]
hyperlocal =  { version = "0.1.4", package = "hyper-unix-connector" }

[target.'cfg(windows)'.dependencies]
mio-named-pipes = "0.1.6"
winapi = "0.3.8"
