[package]
name = "boondock"
description = "Docker daemon API (a fork of Graham Lee's rust-docker)"
version = "0.0.44"
authors = ["Graham Lee <ghmlee@ghmlee.com>",
           "Toby Lawrence <toby@nuclearfurnace.com>",
           "Eric Kidd <git@randomhacks.net>"]
license = "Apache-2.0"
homepage = "https://github.com/faradayio/bookdock"
repository = "https://github.com/faradayio/bookdock"
documentation = "https://docs.rs/boondock"
readme = "README.md"
keywords = ["docker"]

[features]
# OpenSSL is fairly hard to build on certain platforms, especially if you
# want to produce release binaries.  So we enable it by default, but allow
# it to be excluded using `default-features = false`.
default = ["ssl"]

# Enable OpenSSL both directly and for Hyper.
ssl = ["openssl", "hyper/ssl"]

[dependencies]
error-chain = "0.5.0"
hyper = { version = "0.9", default-features = false }
openssl = { version = "0.7", optional = true }
rustc-serialize = "0.3.16"

[target.'cfg(unix)'.dependencies]
unix_socket = "0.5.0"

[target.'cfg(windows)'.dependencies]
named_pipe = "0.2.2"
