[package]
name = "docker"
description = "Docker Remote API binding in Rust"
version = "0.0.11"
authors = ["Graham Lee <ghmlee@ghmlee.com>"]
license = "Apache-2.0"
homepage = "https://github.com/ghmlee/rust-docker"
repository = "https://github.com/ghmlee/rust-docker.git"
documentation = "https://ghmlee.github.io/rust-docker/doc/docker"
readme = "README.md"
keywords = ["docker"]

[lib]
name = "docker"
path = "src/lib.rs"

[dependencies]
unix_socket = "0.3.0"
rustc-serialize = "0.3.12"

[[bin]]
name = "docker"
test = false
doc = false
path = "src/main.rs"