[package]
name = "bollard"
description = "An asynchronous Docker daemon API"
version = "0.3.3"
authors = ["Graham Lee <ghmlee@ghmlee.com>",
           "Toby Lawrence <toby@nuclearfurnace.com>",
           "Eric Kidd <git@randomhacks.net>",
	   "Niel Drummond <niel@drummond.lu>"]
license = "Apache-2.0"
homepage = "https://github.com/fussybeaver/bollard"
repository = "https://github.com/fussybeaver/bollard"
documentation = "https://docs.rs/bollard"
readme = "README.md"
keywords = ["docker"]
edition = "2018"

[features]
# Enable OpenSSL both directly and for Hyper
ssl = ["openssl", "hyper-openssl"]
# Enable native-tls both directly for Hyper
tls = ["native-tls", "hyper-tls"]
# Enable tests specifically for the http connector
test_http = []
# Enable tests specifically for the tls connector
test_tls = []

[dependencies]
arrayvec = "0.4.10"
base64 = "0.10.0"
bytes = "0.4.12"
chrono = { version = "0.4.6", features = ["serde"] }
dirs = "1.0.5"
env_logger = "0.6.1"
failure = "0.1.5"
futures-core-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
hex = "0.3.2"
http = "0.1.17"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-openssl = { version = "0.8.0-alpha.4", optional = true }
hyper-tls = { version = "0.4.0-alpha.4", optional = true }
log = "0.4.6"
mio = "0.6.16"
native-tls = { version = "0.2.3", optional = true }
openssl = { version = "0.10.22", optional = true }
pin-project = "0.4"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
tokio = "0.2.0-alpha.6"
tokio-codec = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
tokio-timer = "0.3.0-alpha.6"
url = "1.7.2"
yup-hyper-mock = "3.15.0"

[dev-dependencies]
tokio-executor = "0.2.0-alpha.6"
flate2 = "1.0"
tar = "0.4.20"

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.6.0"

[target.'cfg(windows)'.dependencies]
mio-named-pipes = "0.1.6"
winapi = "0.3.7"
