version: 2

jobs:
  test_ssl:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker create -v /certs --name certs alpine:3.4 /bin/true
      - run: docker run --rm -e SSL_SUBJECT=test.example.com --volumes-from certs paulczar/omgwtfssl
      - run: docker run --rm -h test.example.com --volumes-from certs -d --privileged --name test-docker-daemon docker:stable-dind --storage-driver=overlay --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/cert.pem --tlskey=/certs/key.pem
      - run: docker build -t boondock .
      - run: docker run -e -ti -e DOCKER_CERT_PATH=/certs -e DOCKER_HOST='tcp://test.example.com:2375' --volumes-from certs --rm --link test-docker-daemon:docker boondock cargo test --features ssl -- --test-threads 1
  test_http:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker run --rm -h test.example.com -d --privileged --name test-docker-daemon docker:stable-dind --storage-driver=overlay
      - run: docker build -t boondock .
      - run: docker run -e -ti -e DOCKER_HOST='tcp://test.example.com:2375' --rm --link test-docker-daemon:docker boondock cargo test --features test_http -- --test-threads 1
  test_unix:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t boondock .
      - run: docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm boondock cargo test -- --test-threads 1


workflows:
  version: 2
  test-image:
    jobs:
      - test_ssl
      - test_http
      - test_unix
